// bible-explored-react/src/features/navigation/Navigation.tsx
import React from 'react'
import { useSelector, useDispatch } from 'react-redux';
import { Link } from 'react-router-dom';

import {
  MENU_HOME,
  MENU_BOOKS_AND_CHAPTERS,
  MENU_VERSE_OF_THE_DAY,
  MENU_SIDE_BY_SIDE
} from '../../common/constants';

import { RootState } from '../../app/store';
import { toggleTheme } from '../../app/parentSlice';

import { ReactComponent as BibleIcon } from '../../res/icons/bible-icon.svg';
import { ReactComponent as IdeaIcon } from '../../res/icons/idea-icon.svg';
import { ReactComponent as SideBySideIcon } from '../../res/icons/compare-svgrepo-com.svg';

import Toggler from '../../common/components/toggler/Toggler';

import './Navigation.scss';

function Navigation() {
  const theme = useSelector((state: RootState) => state.parent.theme);
  const selectedMenu = useSelector((state: RootState) => state.parent.selectedMenu);
  const dispatch = useDispatch();

  const toggleThemeAction = () => {
    dispatch(toggleTheme());
  }

  return (
    <div className='navigation'>
      <div className='header-links'>
        <Link to={`/${MENU_HOME}`}>
          <h1>BIBLE EXPLORED</h1>
        </Link>
        <div className='header-icons'>
          <Link to={`/${MENU_BOOKS_AND_CHAPTERS}`}>
            <BibleIcon className={MENU_BOOKS_AND_CHAPTERS === selectedMenu ? 'selected' : ''}/>
          </Link>
          <Link to={`/${MENU_VERSE_OF_THE_DAY}`}>
            <IdeaIcon className={MENU_VERSE_OF_THE_DAY === selectedMenu ? 'selected' : ''}/>
          </Link>
          <Link to={`/${MENU_SIDE_BY_SIDE}`}>
            <SideBySideIcon className={MENU_SIDE_BY_SIDE === selectedMenu ? 'selected' : ''}/>
          </Link>
        </div>
      </div>
      <Toggler 
        className='theme-toggler' 
        label={<p>Switch to <span>{`${theme === 'light' ? 'Dark' : 'Light'} Mode`}</span></p>}
        defaultValue={theme === 'light'}
        onToggleValue={toggleThemeAction}
      />
    </div>
  )
}

export default Navigation

// bible-explored-angular/src/app/navigation/navigation.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { ThemeService } from '../services/theme/theme.service';
import {
   MENU_HOME,
   MENU_BOOKS_AND_CHAPTERS,
   MENU_VERSE_OF_THE_DAY,
   MENU_SIDE_BY_SIDE
} from '../shared/constants';
import { MenuGroup } from '../shared/types';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.scss']
})
export class NavigationComponent implements OnInit, OnDestroy {
  theme: string = '';
  menuGroup: MenuGroup = {
    menuHome: MENU_HOME,
    menuBooksAndChapters: MENU_BOOKS_AND_CHAPTERS,
    menuVerseOfTheDay: MENU_VERSE_OF_THE_DAY,
    menuSideBySide: MENU_SIDE_BY_SIDE
  }
  private themeSubscription: Subscription = new Subscription();

  constructor(private themeService: ThemeService) {}

  ngOnInit(): void {
      this.themeSubscription = this.themeService.getTheme().subscribe(
        theme => this.theme = theme
      )
  }

  ngOnDestroy(): void {
      if (this.themeSubscription) {
        this.themeSubscription.unsubscribe();
      }
  }

  onToggleTheme() {
    this.themeService.toggleTheme();
  }
}

<div class="navigation">
  <div class="header-links">
    <a routerLink="/{{menuGroup.menuHome}}">
      <h1>BIBLE EXPLORED</h1>
    </a>
    <div class="header-icons">
      <a routerLink="/{{menuGroup.menuBooksAndChapters}}">
        <img src="assets/icons/bible-icon.svg" alt="books and chapters">
      </a>
      <a routerLink="/{{menuGroup.menuVerseOfTheDay}}">
        <img src="assets/icons/idea-icon.svg" alt="verse of the day icon">
      </a>
      <a routerLink="/{{menuGroup.menuSideBySide}}">
        <img src="assets/icons/compare-svgrepo-com.svg" alt="side by side icon">
      </a>
    </div>
  </div>
  <div class="generic-toggler-parent theme-toggler" [ngClass]="theme === 'light' ? 'toggler-true' : 'toggler-false'">
    <p>Switch to <span>{{theme === 'light' ? 'Dark' : 'Light'}} Mode</span></p>
    <div class="toggler-track" (click)="onToggleTheme()">
      <div class="toggler-thumb"></div>
    </div>
  </div>
</div>
