// bible-explored-angular/src/app/shared/components/spinner/spinner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-spinner',
  templateUrl: './spinner.component.html',
  styleUrls: ['./spinner.component.scss']
})
export class SpinnerComponent {
  @Input() width?: string;
  @Input() customClass?: string;
}

<div class="spinner-wrapper" [ngClass]="customClass ? customClass : ''">
  <img class="spinner" src="assets/images/loading.gif" alt="loading..." [ngStyle]="width ? {'width': width} : {}"/>
</div>

// bible-explored-react/src/common/components/spinner/Spinner.tsx
import React from 'react'
import PropTypes from 'prop-types'

import spinnerGif from '../../../res/images/loading.gif'

import './Spinner.scss';

type Props = {
  width?: number
}


function Spinner({width}: Props) {
  return (
    <div className='spinner-wrapper'>
      <img 
        className='spinner' 
        src={spinnerGif} alt='loading...' 
        style={{width: width}}
      />
    </div>
  )
}

Spinner.propTypes = {
  width: PropTypes.string
}

export default Spinner
