// bible-explored-react/src/features/booksAndChapters/BooksAndChapters.jsx
import React from 'react'

import Content from '../../common/components/content/Content'
import DropDown from '../../common/components/dropdown/DropDown'
import Spinner from '../../common/components/spinner/Spinner';

import { useGetBiblesQuery } from '../../services/bibleExplored';


import './BooksAndChapters.scss';

function BooksAndChapters() {
  const { data, error, isLoading } = useGetBiblesQuery();

  const renderBibleGroups = bibleGroups => {
    return (
      bibleGroups.map(bibleGroup => (
        <div className='bible-group' key={bibleGroup.languageId}>
          <p>{bibleGroup.languageName}</p>
          <ul>
            {bibleGroup.bibles.map(bible => (
              <li title={bible.bibleName} key={bible.bibleId}>{bible.bibleName}</li>
            ))}
          </ul>
        </div>
      ))
    )
  }

  return (
    <Content>
      <div className='content books-and-chapters'>
        <div className='bible-select-area'>
          <DropDown className='bible-select' placeHolder='Select a Bible Version'>
            {isLoading && <Spinner />}
            {data && renderBibleGroups(data)}
          </DropDown>
          <input type='button' value='GO'/>
        </div>
      </div>
    </Content>
  )
}

export default BooksAndChapters

// bible-explored-angular/src/app/books-and-chapters/books-and-chapters.component.ts
import { Component, OnInit } from '@angular/core';
import { BibleService } from '../services/bible/bible.service';
import { GroupOption } from '../shared/types';
import { DropdownModel } from '../shared/components/dropdown/dropdown.component';

@Component({
  selector: 'app-books-and-chapters',
  templateUrl: './books-and-chapters.component.html',
  styleUrls: ['./books-and-chapters.component.scss']
})
export class BooksAndChaptersComponent implements OnInit{
  bibleSelectorInput: DropdownModel = {
    parentClass: 'bible-select',
    placeholder: 'Select a Bible Version'
  };
  isLoading = {
    bibles: false,
    books: false,
    chapters: false,
    content: false
  }
  isError = {
    bibles: false,
    books: false,
    chapters: false,
    content: false
  }
  bibleVersion: string = '';

  constructor(private bibleService: BibleService) {}

  ngOnInit(): void {
    this.getBibleVersions();
  }

  getBibleVersions(): void {
    this.isLoading.bibles = true;
    this.bibleService.getBibles().subscribe({
      next: bibleVersions => {
        this.bibleSelectorInput.options = bibleVersions
        this.isLoading.bibles = false;
      },
      error: error => {
        this.isError.bibles = true
        this.isLoading.bibles = false;
      }
    })
  }

  selectBibleVersion(newVersion: string) {
    this.bibleVersion = newVersion;
  }

  loadBooksAndChapters() {

  }
}

<div class="content books-and-chapters">
  <div class="bible-select-area">
    <app-dropdown 
      [dropdownInput]="bibleSelectorInput" 
      [isOptionsLoading]="isLoading.bibles" 
      [isOptionsError]="isError.bibles"
      (selectItemEvent)="selectBibleVersion($event)"
    >
    </app-dropdown>
    <input type="button" value="GO" (click)="loadBooksAndChapters()"/>
  </div>
  <div class="bible-content-area">
  </div>
</div>
