// bible-explored-angular/src/app/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { ThemeService } from '../services/theme/theme.service';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.scss']
})
export class NavigationComponent {
  constructor(private themeService: ThemeService) {}

  onToggleTheme() {
    this.themeService.toggleTheme();
  }
}

<div class="navigation">
  <div class="header-links">
    <h1>BIBLE EXPLORED</h1>
    <div class="header-icons">
      <img src="assets/icons/bible-icon.svg" alt="books and chapters">
      <img src="assets/icons/idea-icon.svg" alt="verse of the day icon">
      <img src="assets/icons/compare-svgrepo-com.svg" alt="side by side icon">
    </div>
  </div>
  <div class="generic-toggler-parent theme-toggler">
    <p>Switch to <span>Dark Mode</span></p>
    <div class="toggler-track" (click)="onToggleTheme()">
      <div class="toggler-thumb"></div>
    </div>
  </div>
</div>

// bible-explored-react/src/features/navigation/Navigation.js
import React from 'react'

import { ReactComponent as BibleIcon } from '../../res/icons/bible-icon.svg';
import { ReactComponent as IdeaIcon } from '../../res/icons/idea-icon.svg';
import { ReactComponent as SideBySideIcon } from '../../res/icons/compare-svgrepo-com.svg';

import Toggler from '../../common/sass/components/toggler/Toggler';

import './Navigation.scss';

function Navigation() {
  return (
    <div className='navigation'>
      <div className='header-links'>
        <h1>BIBLE EXPLORED</h1>
        <div className='header-icons'>
          <BibleIcon />
          <IdeaIcon />
          <SideBySideIcon />
        </div>
      </div>
      <Toggler 
        className='theme-toggler' 
        label={<p>Switch to <span>Dark Mode.</span></p>}
      />
    </div>
  )
}

export default Navigation
