// bible-explored-angular/src/app/shared/components/dropdown/dropdown.component.ts
import { Component, Input } from '@angular/core';
import { Option, GroupOption } from '../../types';


export type DropdownModel = {
  options: Option[] | GroupOption[],
  parentClass: string,
  zIndex: number,
  isDisabled?: boolean
}

@Component({
  selector: 'app-dropdown',
  templateUrl: './dropdown.component.html',
  styleUrls: ['./dropdown.component.scss']
})
export class DropdownComponent {
  @Input() dropdownInput?: DropdownModel
  isOpen = false;

  toggleOpen() {
    this.isOpen = !this.isOpen;
  }

  selectItem(item: string) {
    console.log('Item Selected', item)
    this.isOpen = false;
  }
}

<div class="generic-dropdown-parent">
  <div class="dropdown-header" (click)="toggleOpen()">
    <span>Sample Value</span>
    <img src="assets/icons/dropdown-arrow.svg" alt="dropdown icon" />
  </div>
  <div class="options" [class.open]="isOpen">
    <ul>
      <li>Item 1</li>
      <li>Item 2</li>
    </ul>
  </div>
</div>

// bible-explored-react/src/common/components/dropdown/DropDown.tsx
import React, { useState, ReactNode } from 'react'
import PropTypes from 'prop-types'
import classNames from 'classnames'

import { ReactComponent as DropDownIcon } from '../../../res/icons/dropdown-arrow.svg';

import './DropDown.scss';

type Props = {
  className?: string,
  children: ReactNode,
  placeHolder?: string,
  value: string
}

function DropDown({className, children, placeHolder='Select an Option', value}: Props) {
  const [isOpen, toggleOpen] = useState(false);

  const handleDropDownClick = () => {
    toggleOpen(!isOpen);
  }

  return (
    <div className={classNames('generic-dropdown-parent', className)}>
      <div className='dropdown-header' onClick={handleDropDownClick}>
        <span>{value ? value : placeHolder}</span>
        <DropDownIcon />
      </div>
      <div className={classNames('options', isOpen && 'open')}>
        {children}
      </div>
    </div>
  )
}

DropDown.propTypes = {
  className: PropTypes.string,
  placeHolder: PropTypes.string
}

export default DropDown
